// const ActionTypes = {
//   LOGIN_SUCCESS: "LOGIN_SUCCESS",
//   LOGOUT: "LOGOUT",
//   REGISTER_SUCCESS: "REGISTER_SUCCESS",
//   SAVE_ELECTION_SUCCESS: "SAVE_ELECTION_SUCCESS",
//   SAVE_ELECTION_ERROR: "SAVE_ELECTION_ERROR",
//   CREATE_ELECTION_SUCCESS: "CREATE_ELECTION_SUCCESS",
//   CREATE_ELECTION_ERROR: "CREATE_ELECTION_ERROR",
// };
